<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="gani" failures="1" tests="3" name="Test" time="63.433" errors="0" timestamp="2024-09-15T23:00:53 IST">
  <testcase classname="contacts.CreateContactWithLeadSourceTest" name="createContactWithLeadSource" time="6.297"/>
  <testcase classname="contacts.CreateContactUsingCommonDataAndTestDataTest" name="createContactUsingCommonDataAndTestData" time="5.771">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at contacts.CreateContactUsingCommonDataAndTestDataTest.createContactUsingCommonDataAndTestData(CreateContactUsingCommonDataAndTestDataTest.java:32)
at java.base/java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createContactUsingCommonDataAndTestData -->
  <testcase classname="contacts.DeleteAllContactsTest" name="deleteAllContacts" time="5.426"/>
  <testcase classname="genericUtilities.BaseClass" name="@AfterSuite dataBaseConnectionClose" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite dataBaseConnectionClose -->
  <testcase classname="genericUtilities.BaseClass" name="@BeforeSuite dataBaseConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite dataBaseConnection -->
  <testcase classname="genericUtilities.BaseClass" name="@BeforeSuite dataBaseConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite dataBaseConnection -->
  <testcase classname="genericUtilities.BaseClass" name="@AfterSuite dataBaseConnectionClose" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite dataBaseConnectionClose -->
</testsuite> <!-- Test -->
